/obj/machinery/vending/clothing
	skyrat_product_categories = list(
		list(
			"name" = "Head",
			"icon" = "hat-cowboy",
			"products" = list(
				/obj/item/clothing/head/beret/badge = 5,
				/obj/item/clothing/head/beret/clown/rainbow = 5,
				/obj/item/clothing/head/colourable_flatcap= 5,
				/obj/item/clothing/head/cowboy/skyrat/cattleman = 5,
				/obj/item/clothing/head/cowboy/skyrat/cattleman/wide = 5,
				/obj/item/clothing/head/cowboy/skyrat/wide = 5,
				/obj/item/clothing/head/cowboy/skyrat/wide/feathered = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/cowl = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/sheriff = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/deputy = 5,
				/obj/item/clothing/head/cowboy/skyrat/flat/cowl/sheriff = 5,
				/obj/item/clothing/head/fedora= 5,
				/obj/item/clothing/head/fedora/brown = 5,
				/obj/item/clothing/head/fedora/beige = 5,
				/obj/item/clothing/head/fedora/white = 5,
				/obj/item/clothing/head/hooded/standalone_hood = 5,
				/obj/item/clothing/head/small_bow = 5,
				/obj/item/clothing/head/large_bow = 5,
				/obj/item/clothing/head/back_bow = 5,
				/obj/item/clothing/head/sweet_bow = 5,
			),
		),

		list(
			"name" = "Accessories",
			"icon" = "glasses",
			"products" = list(
				/obj/item/clothing/neck/ranger_poncho = 5,
				/obj/item/clothing/neck/cloak/colourable = 5,
				/obj/item/clothing/neck/cloak/colourable/veil = 5,
				/obj/item/clothing/neck/cloak/colourable/shroud = 5,
				/obj/item/clothing/neck/cloak/colourable/boat = 5,
				/obj/item/clothing/neck/mantle/recolorable = 5,
				/obj/item/clothing/neck/long_cape = 5,
				/obj/item/clothing/neck/wide_cape = 5,
				/obj/item/clothing/neck/robe_cape = 5,
				/obj/item/clothing/glasses/regular/betterunshit = 5,
				/obj/item/clothing/glasses/thin = 5,
				/obj/item/clothing/glasses/hud/ar/projector = 5,
				/obj/item/clothing/neck/face_scarf = 5,
				/obj/item/clothing/gloves/bracer/wraps,
			),
		),

		list(
			"name" = "Under",
			"icon" = "shirt",
			"products" = list(
				/obj/item/clothing/under/pants/skyrat/jeans_ripped = 5,
				/obj/item/clothing/under/shorts/skyrat/shorts_ripped = 5,
				/obj/item/clothing/under/pants/skyrat/yoga = 5,
				/obj/item/clothing/under/misc/skyrat/mechanic = 5,
				/obj/item/clothing/under/misc/bluetracksuit = 5,
				/obj/item/clothing/under/suit/skyrat/recolorable = 5,
				/obj/item/clothing/under/suit/skyrat/recolorable/skirt = 5,
				/obj/item/clothing/under/pants/skyrat/kilt = 5,
				/obj/item/clothing/under/costume/skyrat/kilt/royal = 5,
				/obj/item/clothing/under/costume/skyrat/tac/irish = 5,
				/obj/item/clothing/under/suit/fancy = 5,
				/obj/item/clothing/under/texas = 5,
				/obj/item/clothing/under/sweater = 5,
				/obj/item/clothing/under/sweater/keyhole = 5,
				/obj/item/clothing/under/tachawaiian = 5,
				/obj/item/clothing/under/tachawaiian/purple = 5,
				/obj/item/clothing/under/tachawaiian/green = 5,
				/obj/item/clothing/under/tachawaiian/blue = 5,
				/obj/item/clothing/under/suit/skyrat/black_really_collared = 3,
				/obj/item/clothing/under/suit/skyrat/black_really_collared/skirt = 3,
				/obj/item/clothing/under/suit/skyrat/pencil = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/black_really = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/charcoal = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/navy = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/burgandy = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/checkered = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/tan = 3,
				/obj/item/clothing/under/suit/skyrat/pencil/green = 3,
				/obj/item/clothing/under/suit/skyrat/inferno = 3,
				/obj/item/clothing/under/suit/skyrat/inferno/skirt = 3,
				/obj/item/clothing/under/suit/skyrat/helltaker = 3,
				/obj/item/clothing/under/suit/skyrat/helltaker/skirt = 3,
				/obj/item/clothing/under/dress/skirt/skyrat/medium = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/long = 5,
			),
		),

		list(
			"name" = "Suits & Skirts",
			"icon" = "vest",
			"products" = list(
				/obj/item/clothing/under/dress/skirt/skyrat/lone_skirt = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/turtleskirt_knit = 5,
				/obj/item/clothing/under/dress/skyrat/short_dress = 5,
				/obj/item/clothing/under/dress/skyrat/pinktutu = 5,
				/obj/item/clothing/under/dress/skirt/skyrat/jean = 5,
				/obj/item/clothing/under/dress/skyrat/flower = 5,
				/obj/item/clothing/under/dress/skyrat/strapless = 5,
				/obj/item/clothing/under/dress/skyrat/pentagram = 5,
				/obj/item/clothing/suit/varsity = 5,
				/obj/item/clothing/suit/toggle/jacket = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/gags = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/red = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/aqua = 5,
				/obj/item/clothing/suit/toggle/jacket/flannel/brown = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/trim/alt = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/cti = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/mu = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/smw = 5,
				/obj/item/clothing/suit/toggle/jacket/hoodie/branded/nrti = 5,
				/obj/item/clothing/suit/toggle/jacket/cardigan = 5,
				/obj/item/clothing/suit/toggle/peacoat = 5,
				/obj/item/clothing/suit/toggle/trackjacket = 5,
				/obj/item/clothing/suit/toggle/lawyer/white = 5,
				/obj/item/clothing/suit/urban = 5,
				/obj/item/clothing/suit/duster = 5,
				/obj/item/clothing/suit/fallsparka = 5,
				/obj/item/clothing/suit/croptop = 5,
				/obj/item/clothing/suit/modernwintercoatthing = 5,
				/obj/item/clothing/suit/hooded/wintercoat/colourable = 5,
				/obj/item/clothing/suit/apron/chef/colorable_apron = 5,
				/obj/item/clothing/suit/warm_coat = 5,
				/obj/item/clothing/suit/warm_sweater = 5,
				/obj/item/clothing/suit/heart_sweater = 5,
			),
		),

		list(
			"name" = "Shoes",
			"icon" = "socks",
			"products" = list(
				/obj/item/clothing/shoes/colorable_laceups = 5,
				/obj/item/clothing/shoes/colorable_sandals = 5,
				/obj/item/clothing/shoes/sports = 5,
				/obj/item/clothing/shoes/wraps/colourable = 5,
				/obj/item/clothing/shoes/wraps/cloth = 5,
				/obj/item/clothing/shoes/jungleboots = 5,
				/obj/item/clothing/shoes/jackboots/knee = 5,
				/obj/item/clothing/shoes/jackboots/recolorable = 5,
			),
		),

		//Only put clothing in Special thats either Families or exteremly out-of-place
		list(
			"name" = "Special",
			"icon" = "star",
			"products" = list(
				/obj/item/clothing/under/costume/deckers/alt = 5,
				/obj/item/clothing/under/costume/skyrat/bathrobe = 5,
				/obj/item/clothing/mask/gas/respirator = 5,
				/obj/item/clothing/mask/surgical/greyscale = 5,
			)
		)
	)

	skyrat_premium = list( //being here means you're artificially rare, congratulations
		/obj/item/clothing/shoes/jackboots/timbs = 2,
		/obj/item/clothing/head/soft/yankee = 3,
		/obj/item/clothing/suit/brownbattlecoat = 1,
		/obj/item/clothing/suit/blackfurrich = 1,
		/obj/item/clothing/suit/frenchtrench = 1,
	)
