#define SHOCK_STAGE_MINOR 20
#define SHOCK_STAGE_MODERATE 30
#define SHOCK_STAGE_MAJOR 40
#define BASE_FLOW_RATE 75
#define BASE_FLOW_RATE_UPPER 90
#define FLOW_RATE_ARREST 300
#define FLOW_RATE_DEAD 0
