mode = "BitmaskSlice"

produce_dirs = false
smooth_diagonally = true

[icon_size]
x = 32
y = 32

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 32
y = 32

[positions]
convex = 0
concave = 1
horizontal = 2
vertical = 3
flat = 4

[cut_pos]
x = 16
y = 0
