//as of:10/28/2019:
//boxstation: ~153 loot items spawned
//metastation: ~183 loot items spawned
//deltastation: ~165 loot items spawned

//how to balance maint loot spawns:
// 1) Ensure each category has items of approximately the same power level
// 2) Tune weight of each category until average power of a maint loot spawn is acceptable
// 3) Mapping considerations - Loot value should scale with difficulty of acquisition, or an assistaint will run through collecting free gear with no risk

//goal of maint loot:
// 1) Provide random equipment to people who take effort to crawl maint
// 2) Create memorable moments with very rare, crazy items

//Loot tables

GLOBAL_LIST_INIT(trash_loot, list(//junk: useless, very easy to get, or ghetto chemistry items
	list(// literal trash
		/obj/item/broken_bottle = 1,
		/obj/item/cigbutt = 1,
		/obj/item/cigbutt/roach = 1,
		/obj/item/cigbutt/cigarbutt = 1,
		/obj/item/stack/pipe_cleaner_coil/cut/random = 1,
		/obj/item/ectoplasm = 1,
		/obj/item/ectoplasm/angelic = 1,
		/obj/item/evidencebag = 1,
		/obj/item/food/breadslice/moldy = 1,
		/obj/item/food/deadmouse = 1,
		/obj/item/food/spiderling = 1
		/obj/item/grown/bananapeel = 1,
		/obj/item/grown/bananapeel/bluespace = 1,
		/obj/item/grown/corncob = 1,
		/obj/item/inflatable/torn = 1,
		/obj/item/inflatable/torn/door = 1
		/obj/item/light/bulb/broken = 1,
		/obj/item/light/tube/broken = 1,
		/obj/item/paper/crumpled = 1,
		/obj/item/shard = 1,
		/obj/item/stack/ore/slag = 1,
		/obj/item/storage/bag/trash/filled = 1,
		/obj/item/trash/bee = 1,
		/obj/item/trash/boritos = 1,
		/obj/item/trash/can/food/peaches/maint = 1,
		/obj/item/trash/can/food/beans = 1,
		/obj/item/trash/can = 1,
		/obj/item/trash/candle = 1,
		/obj/item/trash/candy = 1,
		/obj/item/trash/cheesie = 1,
		/obj/item/trash/chips = 1,
		/obj/item/trash/energybar = 1,
		/obj/item/trash/pistachios = 1,
		/obj/item/trash/plate = 1,
		/obj/item/trash/popcorn = 1,
		/obj/item/trash/raisins = 1,
		/obj/item/trash/semki = 1,
		/obj/item/trash/sosjerky = 1,
		/obj/item/trash/syndi_cakes = 1,
		/obj/item/trash/tray = 1,
		/obj/item/trash/waffles = 1,


	) = 100,
	list(//not so literal trash
		/obj/item/c_tube = 1,
		/obj/item/candle = 1,
		/obj/item/stack/pipe_cleaner_coil/random = 1,
		/obj/item/tape/random = 1,
		/obj/item/clothing/head/cone = 1,
		/obj/item/clothing/mask/cigarette = 1,
		/obj/item/clothing/mask/cigarette/carp = 1,
		/obj/item/clothing/mask/cigarette/cigar = 1,
		/obj/item/clothing/mask/cigarette/cigar/cohiba = 1,
		/obj/item/clothing/mask/cigarette/cigar/havana = 1,
		/obj/item/clothing/mask/cigarette/dromedary = 1,
		/obj/item/clothing/mask/cigarette/robust = 1,
		/obj/item/clothing/mask/cigarette/robustgold = 1,
		/obj/item/clothing/mask/cigarette/rollie/cannabis = 1,
		/obj/item/clothing/mask/cigarette/rollie/mindbreaker = 1,
		/obj/item/clothing/mask/cigarette/rollie/nicotine = 1,
		/obj/item/clothing/mask/cigarette/rollie/trippy = 1,
		/obj/item/clothing/mask/cigarette/shadyjims = 1,
		/obj/item/clothing/mask/cigarette/space_cigarette = 1,
		/obj/item/clothing/mask/cigarette/syndicate = 1,
		/obj/item/clothing/mask/cigarette/uplift = 1,
		/obj/item/clothing/mask/cigarette/xeno = 1,
		/obj/item/clothing/mask/vape = 1,
		/obj/item/flashlight/glowstick = 1,
		/obj/item/food/spiderleg = 1,
		/obj/item/kitchen/fork/plastic = 1,
		/obj/item/kitchen/knife/plastic = 1,
		/obj/item/kitchen/spoon/plastic = 1,
		/obj/item/light/bulb = 1,
		/obj/item/light/tube = 1,
		/obj/item/paper/pamphlet/violent_video_games = 1,
		/obj/item/photo/old = 1,
		/obj/item/reagent_containers/food/drinks/bottle/pruno = 1,
		/obj/item/reagent_containers/food/drinks/colocup = 1,
		/obj/item/reagent_containers/glass/bucket = 1,
		/obj/item/reagent_containers/glass/rag = 1 ,
		/obj/item/sign = 1,
		/obj/item/staff/broom = 1,
		/obj/item/storage/bag/tray = 1,
		/obj/item/storage/bag/tray/cafeteria = 1,
		/obj/item/storage/bag/trash = 1,
		/obj/item/toner = 1,
		/obj/item/wirerod = 1,


	) = 80,
	list( //Common maint stuff. Stuff for the greytide.
		/obj/item/airlock_painter = 1,
		/obj/item/airlock_painter/decal = 1,
		/obj/item/book/manual/random = 5,
		/obj/item/book/random = 5,
		/obj/item/poster/random_contraband = 20,
		/obj/item/poster/random_official = 10,
		/obj/item/assembly/shock_kit = 1,
		/obj/item/camera = 2,
		/obj/item/caution = 1,
		/obj/item/chair/plastic = 1,
		/obj/item/clothing/ears/earmuffs = 1,
		/obj/item/clothing/glasses/blindfold = 1,
		/obj/item/clothing/mask/muzzle = 1,
		/obj/item/storage/wallet/random = 5,
		/obj/item/clothing/head/hardhat = 10,
		/obj/item/clothing/head/hardhat/red = 5
		/obj/item/clothing/mask/balaclava = 1,
		/obj/item/clothing/mask/russian_balaclava = 1,
		/obj/item/clothing/mask/bandana/black = 1,
		/obj/item/clothing/mask/breath = 10,
		/obj/item/clothing/mask/fakemoustache = 5,
		/obj/item/clothing/mask/gas = 50,
		/obj/item/clothing/mask/gas/glass = 30,
		/obj/item/clothing/mask/gas/cyborg = 10,
		/obj/item/clothing/mask/gas/plaguedoctor = 5,
		/obj/item/clothing/mask/gas/sechailer = 5,
		/obj/item/clothing/mask/gas/welding = 5,
		/obj/item/clothing/mask/luchador = 1,
		/obj/item/clothing/mask/luchador/rudos = 1,
		/obj/item/clothing/mask/luchador/tecnicos = 1,
		/obj/item/clothing/mask/surgical = 10,
		/obj/item/cultivator/rake = 1,
		/obj/item/disk/data/cloning = 1,
		/obj/item/extinguisher = 1,
		/obj/item/extinguisher/mini = 1,
		/obj/item/flashlight/flare = 1,
		/obj/item/food/butter/on_a_stick = 1,
		/obj/item/food/canned = 1,
		/obj/item/food/canned/beans = 1,
		/obj/item/food/canned/peaches/maint = 1,
		/obj/item/food/chewable/spiderlollipop = 1,
		/obj/item/food/rationpack = 1,
		/obj/item/food/syndicake = 1,
		/obj/item/grenade/iedcasing = 1,
		/obj/item/grenade/smokebomb = 1,
		/obj/item/gun/syringe/blowgun = 1,
		/obj/item/hatchet/wooden = 1,
		/obj/item/kitchen/knife/shiv = 1,
		/obj/item/kitchen/knife/shiv/carrot = 1,
		/obj/item/lighter = 1,
		/obj/item/melee/skateboard/improvised = 1,
		/obj/item/pickaxe/rusted = 1,
		/obj/item/pickaxe/improvised = 1,
		/obj/item/picket_sign = 1,
		/obj/item/pipe = 1,
		/obj/item/pitchfork = 1,
		/obj/item/plaque = 1,
		/obj/item/plunger = 1,
		/obj/item/pneumatic_cannon/ghetto = 1,
		/obj/item/radio = 1,
		/obj/item/razor = 1,
		/obj/item/reagent_containers/food/condiment/mayonnaise = 1,
		/obj/item/reagent_containers/food/drinks/beer = 1,
		/obj/item/reagent_containers/food/drinks/bottle/lizardwine = 1,
		/obj/item/reagent_containers/food/drinks/bottle/moonshine = 1,
		/obj/item/reagent_containers/food/drinks/bottle/kong = 1,
		/obj/item/reagent_containers/food/drinks/bottle/vodka = 1,
		/obj/item/reagent_containers/food/drinks/dry_ramen = 1,
		/obj/item/reagent_containers/hypospray/medipen/atropine = 1,
		/obj/item/reagent_containers/hypospray/medipen/blood_loss = 1,
		/obj/item/reagent_containers/hypospray/medipen/ekit = 1,
		/obj/item/reagent_containers/hypospray/medipen/morphine = 1,
		/obj/item/reagent_containers/hypospray/medipen/pumpup = 1,
		/obj/item/reagent_containers/hypospray/medipen/salbutamol = 1,
		/obj/item/reagent_containers/pill/floorpill = 100,
		/obj/item/reagent_containers/spray/cleaner = 10
		/obj/item/reagent_containers/spray/spraytan = 10,
		/obj/item/reagent_containers/syringe/contraband/bath_salts = 1,
		/obj/item/reagent_containers/syringe/contraband/crank = 1,
		/obj/item/reagent_containers/syringe/contraband/fentanyl = 1,
		/obj/item/reagent_containers/syringe/contraband/krokodil = 1,
		/obj/item/reagent_containers/syringe/contraband/methamphetamine = 1,
		/obj/item/reagent_containers/syringe/contraband/morphine = 1,
		/obj/item/reagent_containers/syringe/contraband/space_drugs = 1,
		/obj/item/restraints/handcuffs/cable/zipties = 1,
		/obj/item/shield/riot/buckler = 1,
		/obj/item/skub = 1,
		/obj/item/soap/homemade = 10,
		/obj/item/spear = 1,
		/obj/item/stack/cable_coil = 10,
		/obj/item/stack/sticky_tape = 10,
		/obj/item/storage/backpack/duffelbag = 1,
		/obj/item/storage/backpack = 1,
		/obj/item/storage/backpack/satchel = 1,
		/obj/item/storage/backpack/old = 1,
		/obj/item/storage/belt = 1,
		/obj/item/storage/belt/utility = 1,
		/obj/item/storage/belt/utility/full = 1,
		/obj/item/storage/box/donkpockets = 1,
		/obj/item/storage/box/donkpockets/donkpocketberry = 1,
		/obj/item/storage/box/donkpockets/donkpockethonk = 1,
		/obj/item/storage/box/donkpockets/donkpocketpizza = 1,
		/obj/item/storage/box/donkpockets/donkpocketspicy = 1,
		/obj/item/storage/box/donkpockets/donkpocketteriyaki = 1,
		/obj/item/storage/box/gum/happiness = 1,
		/obj/item/storage/box/gum/nicotine = 1,
		/obj/item/storage/box/lights/bulbs = 1,
		/obj/item/storage/box/lights/mixed = 1,
		/obj/item/storage/box/lights/tubes = 1,
		/obj/item/storage/cans/sixbeer = 1,
		/obj/item/storage/box/monkeycubes = 1,
		/obj/item/storage/box/papersack/meat = 1,
		/obj/item/storage/pill_bottle/floorpill = 1,
		/obj/item/storage/pill_bottle/happy = 1,
		/obj/item/storage/pill_bottle/lsd = 1,
		/obj/item/storage/pill_bottle/stimulant = 1,
		/obj/item/storage/pill_bottle/zoom = 1,
		/obj/item/storage/toolbox/artistic = 1,
		/obj/item/storage/toolbox/electrical = 1,
		/obj/item/storage/toolbox/emergency/turret = 1,
		/obj/item/tank/internals/emergency_oxygen = 1,
		/obj/item/tank/internals/emergency_oxygen/empty = 1,
		/obj/item/tank/internals/emergency_oxygen/engi = 1,
		/obj/item/tank/internals/emergency_oxygen/engi/empty = 1,
		/obj/item/tank/internals/emergency_oxygen/double = 1,
		/obj/item/tank/internals/emergency_oxygen/double/empty = 1,
		/obj/item/tank/internals/anesthetic = 1,
		/obj/item/tank/internals/generic = 1,
		/obj/item/tank/internals/oxygen = 1,
		/obj/item/tank/jetpack/improvised = 1,
		/obj/item/taperecorder = 1,
		/obj/item/weaponcrafting/receiver = 1,
		/obj/item/weaponcrafting/stock = 1







	) = 100,
	list( //Random meh items
		/obj/item/bouquet/poppy = 1,
		/obj/item/bouquet/sunflower = 1,
		/obj/item/bouquet = 1,
		/obj/item/camera_film = 1,
		/obj/item/clipboard = 1,
		/obj/item/clothing/head/cardborg = 1,
		/obj/item/barcodescanner = 1,
		/obj/item/cane = 1,
		/obj/item/clothing/accessory/pocketprotector = 1,
		/obj/item/reagent_containers/food/drinks/soda_cans/random = 10,
		/obj/item/storage/box/ingredients/random = 1,
		/obj/item/bedsheet/random = 5,
		/obj/item/clothing/mask/cigarette/pipe = 1,
		/obj/item/clothing/mask/cigarette/pipe/cobpipe = 1,
		/obj/item/dest_tagger = 1,
		/obj/item/dice/d6/ebony = 1,
		/obj/item/export_scanner = 1,
		/obj/item/folder = 1,
		/obj/item/food/fried_chicken = 1,
		/obj/item/food/salad/validsalad = 1,
		/obj/item/food/soup/spacylibertyduff = 1,
		/obj/item/food/soup/clownstears = 1,
		/obj/item/food/soylentgreen = 1,
		/obj/item/hand_labeler = 1,
		/obj/item/hourglass = 1,
		/obj/item/mop = 1,
		/obj/item/oxygen_candle = 1,
		/obj/item/pipe_painter = 1,
		/obj/item/plant_analyzer = 1,
		/obj/item/price_tagger = 1,
		/obj/item/pushbroom = 1,
		/obj/item/rack_parts = 1,
		/obj/item/radio/headset = 1,
		/obj/item/reagent_containers/food/drinks/coffee = 1,
		/obj/item/reagent_containers/food/drinks/colocup/lean = 1,
		/obj/item/reagent_containers/food/drinks/flask = 1,
		/obj/item/reagent_containers/food/drinks/ice/prison = 1,
		/obj/item/reagent_containers/spray/pestspray = 1,
		/obj/item/reagent_containers/spray/weedspray = 1,
		/obj/item/stack/arcadeticket/thirty = 1,
		/obj/item/stack/medical/gauze/improvised = 1,
		/obj/item/stack/medical/splint/improvised = 1,
		/obj/item/stack/wrapping_paper = 1,
		/obj/item/storage/book/bible = 1,
		/obj/item/storage/book/bible/booze = 1,
		/obj/item/storage/box/gum = 1,
		/obj/item/storage/briefcase = 1,
		/obj/item/storage/secure/briefcase = 1,

	) = 60,
	list( //Random useful stuff that's only useful in large quantities
		/obj/item/food/grown/random = 1,
	) = 40,
	list( //Trash but I don't want to make so much of it.
		/obj/item/kirbyplants/random = 1,
		/obj/item/flashlight/lamp = 1,
		/obj/item/food/american_sausage = 1
		/obj/item/food/branrequests = 1
		/obj/item/paper_bin = 1,
		/obj/item/paper_bin/construction = 1,
		/obj/item/pizzabox/pineapple = 1,
		/obj/item/reagent_containers/food/drinks/bottle/vodka/badminka = 1,
		/obj/item/reagent_containers/food/drinks/bottle/whiskey = 1,
		/obj/item/stack/circuit_stack/full = 10,
		/obj/item/stack/conveyor/thirty = 10,
		/obj/item/stack/ducts/fifty = 10,
		/obj/item/stack/marker_beacon/thirty = 10,
		/obj/item/statuebust = 1,
		/obj/item/storage/box/actionfigure = 1,
		/obj/item/storage/box/bodybags = 1,
		/obj/item/storage/box/clown = 1,
		/obj/item/storage/box/cups = 1,
		/obj/item/storage/box/dishdrive = 1,
		/obj/item/storage/box/disks = 1,
		/obj/item/storage/box/drinkingglasses = 1,
		/obj/item/storage/box/emptysandbags = 1,
		/obj/item/storage/box/evidence = 1,
		/obj/item/storage/box/gloves = 1
		/obj/item/storage/box/masks = 1,
		/obj/item/storage/box/matches = 1,
		/obj/item/storage/box/pillbottles = 1,
		/obj/item/storage/box/plumbing = 1,
		/obj/item/storage/box/shipping = 1,
		/obj/item/storage/box/smart_metal_foam = 1,
		/obj/item/storage/box/stockparts/basic = 1,
		/obj/item/storage/box/syringes = 1,
		/obj/item/storage/box/tail_pin = 1,
		/obj/item/storage/box/vials = 1,
		/obj/item/storage/box/zipties = 1,
		/obj/item/storage/fancy/donut_box = 1,
		/obj/item/storage/fancy/heart_box = 1,
		/obj/item/storage/fancy/rollingpapers = 1,
		/obj/item/wheelchair = 1
	) = 10,
	list( //Circuits
		/obj/item/electronics/airalarm = 10,
		/obj/item/electronics/airlock = 10,
		/obj/item/electronics/apc = 10,
		/obj/item/electronics/firealarm = 1,
		/obj/item/electronics/firelock = 1,
		/obj/item/electronics/tracker = 1
	) = 10,


))



GLOBAL_LIST_INIT(common_loot, list( //common: basic items
	list( //Smoking
		/obj/item/storage/fancy/cigarettes = 1,
		/obj/item/storage/fancy/cigarettes/cigars = 1,
		/obj/item/storage/fancy/cigarettes/cigars/cohiba = 1,
		/obj/item/storage/fancy/cigarettes/cigars/havana = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_cannabis = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_carp = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_midori = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_mindbreaker = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_robust = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_robustgold = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_shadyjims = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_syndicate = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_uplift = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_xeno = 1,
		/obj/item/storage/fancy/cigarettes/dromedaryco = 1
	) = 10,
	list( //Stock parts
		/obj/item/stock_parts/capacitor = 1,
		/obj/item/stock_parts/capacitor/adv = 1,
		/obj/item/stock_parts/cell = 1,
		/obj/item/stock_parts/cell/crap = 1,
		/obj/item/stock_parts/cell/potato = 1,
		/obj/item/stock_parts/cell/upgraded = 1,
		/obj/item/stock_parts/electrolite = 1,
		/obj/item/stock_parts/electrolite/adv = 1,
		/obj/item/stock_parts/manipulator = 1,
		/obj/item/stock_parts/manipulator/nano = 1,
		/obj/item/stock_parts/matter_bin = 1,
		/obj/item/stock_parts/matter_bin/adv = 1,
		/obj/item/stock_parts/micro_laser = 1,
		/obj/item/stock_parts/micro_laser/high = 1,
		/obj/item/stock_parts/scanning_module = 1,
		/obj/item/stock_parts/scanning_module/adv = 1,
		/obj/item/stock_parts/water_recycler = 1
	) = 10,
	list( //Tiles
		/obj/item/stack/tile/bronze/thirty = 1,
		/obj/item/stack/tile/carpet/black/fifty = 1,
		/obj/item/stack/tile/carpet/blue/fifty = 1,
		/obj/item/stack/tile/carpet/cyan/fifty = 1,
		/obj/item/stack/tile/carpet/donk/thirty = 1,
		/obj/item/stack/tile/carpet/executive/thirty = 1,
		/obj/item/stack/tile/carpet/fifty = 1,
		/obj/item/stack/tile/carpet/green/fifty = 1,
		/obj/item/stack/tile/carpet/orange/fifty = 1,
		/obj/item/stack/tile/carpet/purple/fifty = 1,
		/obj/item/stack/tile/carpet/red/fifty = 1,
		/obj/item/stack/tile/carpet/royalblack/fifty = 1,
		/obj/item/stack/tile/carpet/royalblue/fifty = 1,
		/obj/item/stack/tile/carpet/stellar/thirty = 1
		/obj/item/stack/tile/eighties/loaded = 1,
		/obj/item/stack/tile/fakepit/loaded = 1,
		/obj/item/stack/tile/fakespace/loaded = 1,
	) = 50,
	list( //Cash money
		/obj/item/stack/spacecash/c1 = 256,
		/obj/item/stack/spacecash/c10 = 128,
		/obj/item/stack/spacecash/c20 = 64,
		/obj/item/stack/spacecash/c50 = 32,
		/obj/item/stack/spacecash/c100 = 16,
		/obj/item/stack/spacecash/c200 = 8,
		/obj/item/stack/spacecash/c500 = 4
		/obj/item/stack/spacecash/c1000 = 2,
		/obj/item/stack/spacecash/c10000 = 1
	) = 10,
	list( //Construction Material
		/obj/item/stack/ore/glass = 1,
		/obj/item/stack/ore/iron = 1,
		/obj/item/stack/package_wrap = 1,
		/obj/item/stack/rods/ten = 1,
		/obj/item/stack/rods/twentyfive = 1,
		/obj/item/stack/rods/fifty = 1,
		/obj/item/stack/sheet/cardboard = 1,
		/obj/item/stack/sheet/cardboard/fifty = 1,
		/obj/item/stack/sheet/cloth/five = 1,
		/obj/item/stack/sheet/cloth/ten = 1,
		/obj/item/stack/sheet/cotton = 1,
		/obj/item/stack/sheet/glass = 1,
		/obj/item/stack/sheet/glass/fifty = 1,
		/obj/item/stack/sheet/metal/fifty = 1,
		/obj/item/stack/sheet/metal/five = 1,
		/obj/item/stack/sheet/metal/ten = 1,
		/obj/item/stack/sheet/metal/twenty = 1,
		/obj/item/stack/sheet/mineral/bamboo = 1,
		/obj/item/stack/sheet/mineral/coal/five = 1,
		/obj/item/stack/sheet/mineral/coal/ten = 1,
		/obj/item/stack/sheet/mineral/plasma = 1,
		/obj/item/stack/sheet/mineral/diamond = 1,
		/obj/item/stack/sheet/mineral/sandstone/thirty = 1,
		/obj/item/stack/sheet/mineral/wood/fifty = 1,
		/obj/item/stack/sheet/mineral/wood = 1,
		/obj/item/stack/sheet/paperframes/five = 1,
		/obj/item/stack/sheet/paperframes/twenty = 1,
		/obj/item/stack/sheet/paperframes/fifty = 1,
		/obj/item/stack/sheet/pizza/fifty = 1,
		/obj/item/stack/sheet/pizza/five = 1,
		/obj/item/stack/sheet/pizza/twenty = 1,
		/obj/item/stack/sheet/plasmaglass = 1,
		/obj/item/stack/sheet/plasmaglass/fifty = 1,
		/obj/item/stack/sheet/plasmarglass = 1,
		/obj/item/stack/sheet/plasteel = 1,
		/obj/item/stack/sheet/plasteel/fifty = 1,
		/obj/item/stack/sheet/plasteel/twenty = 1,
		/obj/item/stack/sheet/plastic = 1,
		/obj/item/stack/sheet/plastic/fifty = 1,
		/obj/item/stack/sheet/plastic/five = 1,
		/obj/item/stack/sheet/rglass = 1,
		/obj/item/stack/sheet/sandblock = 1,
		/obj/item/stack/sheet/sandblock/fifty = 1,
		/obj/item/stack/sheet/sandblock/five = 1,
		/obj/item/stack/sheet/sandblock/twenty = 1,

	) = 10,
	list( //Hides and fluff stuff
		/obj/item/stack/sheet/animalhide/cat = 1,
		/obj/item/stack/sheet/animalhide/corgi = 1,
		/obj/item/stack/sheet/animalhide/generic = 1,
		/obj/item/stack/sheet/animalhide/human = 1,
		/obj/item/stack/sheet/animalhide/gondola = 1,
		/obj/item/stack/sheet/animalhide/lizard = 1,
		/obj/item/stack/sheet/animalhide/monkey = 1,
		/obj/item/stack/sheet/animalhide/xeno = 1,
		/obj/item/stack/sheet/bone = 1,
		/obj/item/stack/sheet/hairlesshide = 1,
		/obj/item/stack/sheet/leather = 1,
		/obj/item/stack/sheet/wethide = 1,
		/obj/item/stack/sheet/xenochitin = 1,
		/obj/item/stack/sheet/sinew = 1
	) = 10,


	list( //Medical stuff
		/obj/item/hypospray/mkii/tricord = 1,
		/obj/item/healthanalyzer = 1,
		/obj/item/healthanalyzer/wound = 1,
		/obj/item/reagent_containers/blood/random = 5,
		/obj/item/stack/medical/aloe = 1,
		/obj/item/stack/medical/bruise_pack = 1,
		/obj/item/stack/medical/gauze/twelve = 1,
		/obj/item/stack/medical/mesh = 1,
		/obj/item/stack/medical/ointment = 1,
		/obj/item/stack/medical/poultice = 1,
		/obj/item/stack/medical/splint/twelve = 1,
		/obj/item/stack/medical/suture = 1,
		/obj/item/stack/sticky_tape/surgical = 1,
		/obj/item/storage/firstaid = 1,
		/obj/item/storage/firstaid/advanced = 1,
		/obj/item/storage/firstaid/brute = 1,
		/obj/item/storage/firstaid/fire = 1,
		/obj/item/storage/firstaid/medical = 1,
		/obj/item/storage/firstaid/o2 = 1,
		/obj/item/storage/firstaid/regular = 1,
		/obj/item/storage/firstaid/toxin = 1

	) = 40,

	list( //Tools you'd get in tool storage and elsewhere
		/obj/item/screwdriver = 1,
		/obj/item/analyzer = 1,
		/obj/item/assembly/health = 1,
		/obj/item/assembly/igniter = 1,
		/obj/item/assembly/igniter/condenser = 1,
		/obj/item/assembly/infra = 1,
		/obj/item/assembly/mousetrap/armed = 1,
		/obj/item/assembly/prox_sensor = 1,
		/obj/item/assembly/signaler = 1,
		/obj/item/assembly/timer = 1,
		/obj/item/assembly/voice = 1,
		/obj/item/crowbar = 1,
		/obj/item/cultivator = 1,
		/obj/item/flashlight = 1,
		/obj/item/geiger_counter = 1,
		/obj/item/multitool = 1,
		/obj/item/pen = 1,
		/obj/item/shovel = 1,
		/obj/item/shovel/spade = 1
		/obj/item/t_scanner = 1,
		/obj/item/weldingtool = 1,
		/obj/item/wirecutters = 1,
		/obj/item/wrench = 1




	) = 10,
	list( //Stuff you'd get elsewhere but they're not that good
		/obj/item/beacon = 1,
		/obj/item/binoculars = 1,
		/obj/item/bodybag = 1,
		/obj/item/clothing/gloves/radio = 1,
		/obj/item/reagent_containers/blood/random = 10,
		/obj/item/seeds/random = 1,
		/obj/item/electropack = 1,
		/obj/item/extinguisher_refill = 1,
		/obj/item/flamethrower = 1,
		/obj/item/flashlight/lantern = 1,
		/obj/item/flashlight/lantern/jade = 1,
		/obj/item/flashlight/seclite = 1,
		/obj/item/flashlight/pen = 1,
		/obj/item/flashlight/pen/paramedic = 1,
		/obj/item/food/donut/chaos = 1,
		/obj/item/gps/engineering = 1,
		/obj/item/grenade/chem_grenade/cleaner = 1,
		/obj/item/mining_scanner = 1,
		/obj/item/modular_computer/laptop/preset/civilian = 1,
		/obj/item/modular_computer/tablet/preset/cheap = 1,
		/obj/item/oar = 1,
		/obj/item/paint/anycolor = 1,
		/obj/item/pen/fourcolor = 1,
		/obj/item/pen/invisible = 1,
		/obj/item/pen/fountain = 1,
		/obj/item/pen/charcoal = 1,
		/obj/item/roller = 1,
		/obj/item/rollingpaper = 1,
		/obj/item/sales_tagger = 1,
		/obj/item/slime_scanner = 1,
		/obj/item/storage/box/hug/survival = 1,
		/obj/item/storage/box/papersack = 1,
		/obj/item/switchblade = 1,
		/obj/item/ttsdevice = 1,
		/obj/item/watertank = 1,
		/obj/item/watertank/atmos = 1,
		/obj/item/watertank/janitor = 1,

	) = 5,
	list( //FAKE insuls.
		/obj/item/clothing/gloves/color/fyellow = 1,
		/obj/item/clothing/gloves/color/fyellow/old = 1
		/obj/item/clothing/gloves/color/red = 1,
		/obj/item/clothing/gloves/color/black = 1,
		/obj/item/clothing/gloves/fingerless = 1,
		/obj/item/clothing/gloves/tackler/offbrand = 1,

	) = 30,
	list( //Toys, cosmetics, and vanity items.
		/obj/item/bikehorn/rubberducky/plasticducky = 1,
		/obj/item/cardpack/resin = 1,
		/obj/item/cardpack/series_one = 1,
		/obj/item/bikehorn = 1,
		/obj/item/clothing/gloves/boxing = 1,
		/obj/item/clothing/gloves/boxing/blue = 1,
		/obj/item/clothing/gloves/boxing/green = 1,
		/obj/item/clothing/gloves/boxing/yellow = 1,
		/obj/item/clothing/glasses/trickblindfold = 1,
		/obj/item/clothing/mask/facehugger/toy = 1,
		/obj/item/clothing/mask/whistle = 1,
		/obj/item/clothing/neck/beads = 1,
		/obj/item/clothing/shoes/wheelys = 1,
		/obj/item/clothing/shoes/wheelys/rollerskates = 1,
		/obj/item/clothing/shoes/wheelys/skishoes = 1,
		/obj/item/dualsaber/toy = 1,
		/obj/item/extendohand/acme = 1,
		/obj/item/grenade/chem_grenade/glitter/blue = 1,
		/obj/item/grenade/chem_grenade/glitter/pink = 1,
		/obj/item/grenade/chem_grenade/glitter/white = 1,
		/obj/item/gun/ballistic/automatic/c20r/toy/unrestricted = 1,
		/obj/item/gun/ballistic/automatic/l6_saw/toy/unrestricted = 1,
		/obj/item/gun/ballistic/automatic/toy/unrestricted = 1,
		/obj/item/gun/ballistic/automatic/toy/pistol/unrestricted = 1,
		/obj/item/gun/ballistic/shotgun/toy/unrestricted = 1,
		/obj/item/gun/ballistic/shotgun/toy/crossbow = 1,
		/obj/item/hot_potato/harmless/toy = 1,
		/obj/item/instrument/saxophone/spectral = 1,
		/obj/item/instrument/trombone/spectral = 1,
		/obj/item/instrument/trumpet/spectral = 1,
		/obj/item/laser_pointer = 1,
		/obj/item/latexballon = 1,
		/obj/item/megaphone = 1,
		/obj/item/megaphone/clown = 1,
		/obj/item/reagent_containers/spray/waterflower/lube = 10
		/obj/item/reagent_containers/spray/waterflower = 10,
		/obj/item/restraints/handcuffs/fake = 10,
		/obj/item/sparkler = 1,
		/obj/item/storage/belt/military/snack = 1,
		/obj/item/storage/box/snappops = 1,
		/obj/item/storage/box/sparklers = 1,
		/obj/item/storage/card_binder = 1
		/obj/item/storage/crayons = 1,
		/obj/item/storage/fancy/candle_box = 1,
		/obj/item/throwing_star/toy = 1,
		/obj/item/toy/ammo/gun = 1,
		/obj/item/toy/balloon/arrest = 1,
		/obj/item/toy/balloon/corgi = 1,
		/obj/item/toy/balloon/syndicate = 1,
		/obj/item/toy/beach_ball = 1,
		/obj/item/toy/beach_ball/holoball = 1,
		/obj/item/toy/beach_ball/holoball/dodgeball = 1,
		/obj/item/toy/braintoy = 1,
		/obj/item/toy/brokenradio = 1,
		/obj/item/toy/cattoy = 1,
		/obj/item/toy/clockwork_watch = 1,
		/obj/item/toy/crayon/mime = 1,
		/obj/item/toy/crayon/spraycan/lubecan = 1,
		/obj/item/toy/crayon/spraycan/mimecan = 1,
		/obj/item/toy/dummy = 1,
		/obj/item/toy/eightball = 1,
		/obj/item/toy/eightball/broken = 1,
		/obj/item/toy/eightball/haunted = 1,
		/obj/item/toy/foamblade = 1,
		/obj/item/toy/gun = 1,
		/obj/item/toy/katana = 1,
		/obj/item/toy/minimeteor = 1,
		/obj/item/toy/nuke = 1,
		/obj/item/toy/plush/beeplushie = 1,
		/obj/item/toy/plush/bubbleplush = 1,
		/obj/item/toy/plush/carpplushie = 1,
		/obj/item/toy/plush/goatplushie = 1,
		/obj/item/toy/plush/lizardplushie = 1,
		/obj/item/toy/plush/moth = 1,
		/obj/item/toy/plush/narplush = 1,
		/obj/item/toy/plush/nukeplushie = 1,
		/obj/item/toy/plush/pkplush = 1,
		/obj/item/toy/plush/ratplush = 1,
		/obj/item/toy/plush/slimeplushie = 1,
		/obj/item/toy/plush/snakeplushie = 1,
		/obj/item/toy/redbutton = 1,
		/obj/item/toy/seashell = 1,
		/obj/item/toy/snappop = 1,
		/obj/item/toy/snappop/phoenix = 1,
		/obj/item/toy/spinningtoy = 1,
		/obj/item/toy/sword = 1,
		/obj/item/toy/talking/ai = 1,
		/obj/item/toy/talking/codex_gigas = 1,
		/obj/item/toy/talking/griffin = 1,
		/obj/item/toy/talking/owl = 1,
		/obj/item/toy/toy_dagger = 1,
		/obj/item/toy/toy_xeno = 1,
		/obj/item/toy/waterballoon = 1,
		/obj/item/toy/windup_toolbox = 1,
		/obj/item/toy/xmas_cracker = 1,
		/obj/item/training_toolbox = 1


	) = 10,
	list( //Instruments
		/obj/item/instrument/accordion = 1,
		/obj/item/instrument/banjo = 1,
		/obj/item/instrument/bikehorn = 1,
		/obj/item/instrument/eguitar = 1,
		/obj/item/instrument/glockenspiel = 1,
		/obj/item/instrument/guitar = 1,
		/obj/item/instrument/harmonica = 1,
		/obj/item/instrument/piano_synth = 1,
		/obj/item/instrument/piano_synth/headphones = 1,
		/obj/item/instrument/recorder = 1,
		/obj/item/instrument/saxophone = 1,
		/obj/item/instrument/trombone = 1,
		/obj/item/instrument/trumpet = 1,
		/obj/item/instrument/violin = 1

	),
	list( //Unimportant clothing
		/obj/item/clothing/accessory/fan_clown_pin = 1,
		/obj/item/clothing/accessory/fan_mime_pin = 1,
		/obj/item/clothing/accessory/lawyers_badge = 1,
		/obj/item/clothing/accessory/waistcoat = 1,
		/obj/item/clothing/ears/headphones = 1,
		/obj/item/clothing/glasses/blindfold/white = 1,
		/obj/item/clothing/glasses/eyepatch = 1,
		/obj/item/clothing/glasses/heat = 1,
		/obj/item/clothing/head/bearpelt = 1,
		/obj/item/clothing/head/bishopmitre = 1,
		/obj/item/clothing/head/canada = 1,
		/obj/item/clothing/head/wig/random = 10,
		/obj/item/clothing/under/color/jumpskirt/random = 10,
		/obj/item/clothing/under/color/random = 20,
		/obj/item/lipstick/random = 10,
		/obj/item/clothing/head/cueball = 1,
		/obj/item/clothing/head/delinquent = 1,
		/obj/item/clothing/head/fedora/det_hat = 1
		/obj/item/clothing/head/festive = 1,
		/obj/item/clothing/head/intern = 1,
		/obj/item/clothing/head/justice = 1,
		/obj/item/clothing/head/justice/blue = 1,
		/obj/item/clothing/head/justice/green = 1,
		/obj/item/clothing/head/justice/pink = 1,
		/obj/item/clothing/head/justice/yellow = 1,
		/obj/item/clothing/head/kitty/genuine = 1.
		/obj/item/clothing/head/lizard = 1,
		/obj/item/clothing/head/medievaljewhat = 1,
		/obj/item/clothing/head/papersack/smiley = 1
		/obj/item/clothing/head/soft/grey = 10,
		/obj/item/clothing/head/sombrero/green = 1,
		/obj/item/clothing/mask/gas/syndicate = 1,
		/obj/item/clothing/shoes/winterboots/ice_boots = 1,
		/obj/item/clothing/suit/hooded/wintercoat/narsie/fake = 10,
		/obj/item/clothing/suit/hooded/wintercoat/ratvar/fake = 10
		/obj/item/clothing/under/dress/skirt/polychromic = 10,
		/obj/item/clothing/under/dress/skirt/polychromic/pleated = 10,
		/obj/item/clothing/under/misc/poly_bottomless = 10,
		/obj/item/clothing/under/misc/poly_kilt = 10,
		/obj/item/clothing/under/misc/poly_shirt = 10,
		/obj/item/clothing/under/misc/poly_tanktop = 10,
		/obj/item/clothing/under/misc/poly_tanktop/female = 10,
		/obj/item/clothing/under/misc/polyjumpsuit = 10,
		/obj/item/clothing/under/misc/polyshorts = 10,
		/obj/item/clothing/under/shorts/polychromic = 10,
		/obj/item/clothing/under/shorts/polychromic/pantsu = 10,
		/obj/item/clothing/suit/hooded/wintercoat/polychromic = 10
	) = 1,
	list( //Stuff you'd find in maint but like not really
		/obj/item/food/meat/slab/human = 1,
		/obj/item/food/meat/slab/human/mutant/ethereal = 1,
		/obj/item/food/meat/slab/human/mutant/fly = 1,
		/obj/item/food/meat/slab/human/mutant/lizard = 1,
		/obj/item/food/meat/slab/human/mutant/moth = 1,
		/obj/item/food/meat/slab/human/mutant/plant = 1,
		/obj/item/food/meat/slab/human/mutant/shadow = 1,
		/obj/item/food/meat/slab/human/mutant/skeleton = 1,
		/obj/item/food/meat/slab/human/mutant/slime = 1,
		/obj/item/food/meat/slab/human/mutant/zombie = 1
	) = 1,
))



GLOBAL_LIST_INIT(uncommon_loot, list(//uncommon: useful items
	list( //Skillchips
		/obj/item/skillchip/basketweaving = 50,
		/obj/item/skillchip/bonsai = 100,
		/obj/item/skillchip/disk_verifier = 1,
		/obj/item/skillchip/job/engineer = 10,
		/obj/item/skillchip/job/roboticist = 10,
		/obj/item/skillchip/light_remover = 10,
		/obj/item/skillchip/useless_adapter = 25,
		/obj/item/skillchip/wine_taster = 50
	)



	list( //Collectable hats!
		/obj/item/clothing/head/collectable/beret = 1,



	) = 1,
	list( //Cartridges
		/obj/item/cartridge/atmos = 1,
		/obj/item/cartridge/captain = 1,
		/obj/item/cartridge/ce = 1,
		/obj/item/cartridge/chemistry = 1,
		/obj/item/cartridge/cmo = 1,
		/obj/item/cartridge/curator = 1,
		/obj/item/cartridge/detective = 1,
		/obj/item/cartridge/engineering = 1,
		/obj/item/cartridge/head = 1,
		/obj/item/cartridge/hop = 1,
		/obj/item/cartridge/hos = 1,
		/obj/item/cartridge/janitor = 1,
		/obj/item/cartridge/lawyer = 1,
		/obj/item/cartridge/medical = 1,
		/obj/item/cartridge/quartermaster = 1,
		/obj/item/cartridge/rd = 1,
		/obj/item/cartridge/roboticist = 1,
		/obj/item/cartridge/security = 1,
		/obj/item/cartridge/signal = 1,
		/obj/item/cartridge/signal/toxins = 1,
		/obj/item/cartridge/virus/clown = 1,
		/obj/item/cartridge/virus/mime = 1,
	) = 10,
	list( //Bot assemblies
		/obj/item/bot_assembly/cleanbot = 1,
		/obj/item/bot_assembly/ed209 = 1,
		/obj/item/bot_assembly/firebot = 1,
		/obj/item/bot_assembly/floorbot = 1,
		/obj/item/bot_assembly/honkbot = 1,
		/obj/item/bot_assembly/hygienebot = 1,
		/obj/item/bot_assembly/medbot = 1,
		/obj/item/bot_assembly/secbot = 1
	) = 20,
	list( //Surgery stuff
		/obj/item/bonesetter = 1,
		/obj/item/cautery = 1,
		/obj/item/circular_saw = 1,
		/obj/item/defibrillator/loaded = 1,
		/obj/item/hemostat = 1,
		/obj/item/retractor = 1,
		/obj/item/scalpel = 1,
		/obj/item/stack/medical/bone_gel = 1,
		/obj/item/surgical_drapes = 1,
		/obj/item/surgical_processor = 1,
		/obj/item/surgicaldrill = 1,


	) = 40,
	list( //Very useful tools and equipment
		/obj/item/anomaly_neutralizer = 1,
		/obj/item/assembly/flash = 1,
		/obj/item/clothing/glasses/material = 1,
		/obj/item/clothing/glasses/meson = 1
		/obj/item/clothing/glasses/science = 1,
		/obj/item/clothing/glasses/sunglasses = 1,
		/obj/item/clothing/glasses/sunglasses/big = 1,
		/obj/item/clothing/glasses/welding = 100,
		/obj/item/clothing/head/welding = 200,
		/obj/item/clothing/head/hardhat/weldhat = 5,
		/obj/item/clothing/head/helmet = 1,
		/obj/item/clothing/glasses/hud/toggle/thermal = 1,
		/obj/item/clothing/glasses/prism_glasses = 1,
		/obj/item/clothing/suit/armor/vest = 1,
		/obj/item/clothing/gloves/tackler/combat = 1,
		/obj/item/clothing/gloves/tackler/dolphin = 1,
		/obj/item/clothing/gloves/tackler/rocket = 1,
		/obj/item/construction/rcd/loaded = 1,
		/obj/item/construction/rld = 1,
		/obj/item/crucifix = 1,
		/obj/item/detective_scanner = 1,
		/obj/item/door_seal = 1,
		/obj/item/extinguisher/advanced = 1,
		/obj/item/forcefield_projector = 1,
		/obj/item/grenade/barrier = 1,
		/obj/item/grenade/chem_grenade/antiweed = 1,
		/obj/item/grenade/chem_grenade/metalfoam = 1,
		/obj/item/grenade/chem_grenade/smart_metal_foam = 1,
		/obj/item/grenade/chem_grenade/teargas = 1,
		/obj/item/grenade/flashbang = 1,
		/obj/item/holosign_creator/atmos = 1,
		/obj/item/holosign_creator/engineering = 1,
		/obj/item/holosign_creator/medical = 1,
		/obj/item/holosign_creator/security = 1,
		/obj/item/inducer = 1
		/obj/item/language_manual/roundstart_species = 1,
		/obj/item/lazarus_injector = 1,
		/obj/item/melee/baseball_bat = 1,
		/obj/item/melee/baton/cattleprod = 1,
		/obj/item/melee/skateboard/pro = 1,
		/obj/item/melee/skateboard = 1,
		/obj/item/mining_voucher = 1,
		/obj/item/mmi = 1,
		/obj/item/papercutter = 1,
		/obj/item/reagent_containers/food/drinks/bottle/holywater = 1,
		/obj/item/reagent_containers/glass/bottle/traitor = 1,
		/obj/item/restraints/handcuffs = 1,
		/obj/item/stack/ore/bluespace_crystal/artificial = 1,
		/obj/item/storage/box/fireworks = 1,
		/obj/item/storage/box/handcuffs = 1
		/obj/item/toy/cards/deck/syndicate = 1,
		/obj/item/wormhole_jaunter = 1



	) = 50,
	list( //Ammo
		/obj/item/ammo_casing/shotgun/beanbag = 1,
		/obj/item/ammo_casing/shotgun/buckshot = 1,
		/obj/item/ammo_casing/shotgun/improvised = 10,
	) = 1,
	list( // Good memes.
		/obj/item/aicard/aitater = 1,
		/obj/item/a_gift = 1,
		/obj/item/banhammer = 1,
		/obj/item/bikehorn/airhorn = 1,
		/obj/item/blackmarket_uplink = 1,
		/obj/item/book/granter/spell/smoke/lesser = 1,
		/obj/item/bountytrap = 1,
		/obj/item/camera/spooky = 1,
		/obj/item/capturedevice = 1,
		/obj/item/cardboard_cutout/adaptive = 1,
		/obj/item/clothing/head/chefhat/i_am_assuming_direct_control = 1,
		/obj/item/clothing/head/crown = 1,
		/obj/item/clothing/head/foilhat = 1,
		/obj/item/clothing/head/hardhat/cakehat = 1,
		/obj/item/clothing/head/helmet/justice = 1
		/obj/item/clothing/head/helmet/justice/escape = 1,
		/obj/item/clothing/head/peaceflower = 1,
		/obj/item/clothing/mask/fakemoustache/sticky = 1,
		/obj/item/clothing/suit/hooded/flashsuit = 10,
		/obj/item/disk/tech_disk/spaceloot = 1,
		/obj/item/etherealballdeployer = 1,
		/obj/item/firing_pin/clown = 1,
		/obj/item/flashlight/flashdark = 1,
		/obj/item/flashlight/lantern/syndicate = 1,
		/obj/item/food/monkeycube/gorilla = 1,
		/obj/item/food/pizzaslice/arnold = 1,
		/obj/item/greentext/quiet = 1,
		/obj/item/grenade/antigravity = 1,
		/obj/item/grenade/chem_grenade/colorful = 1,
		/obj/item/grenade/chem_grenade/ez_clean = 1,
		/obj/item/grenade/firecracker = 1,
		/obj/item/grenade/stingbang = 1,
		/obj/item/instrument/musicalmoth = 1
		/obj/item/instrument/piano_synth/headphones/spacepods = 1,
		/obj/item/instrument/violin/golden = 1,
		/obj/item/melee/baton/cattleprod/teleprod = 1,
		/obj/item/melee/chainofcommand/tailwhip/kitty = 1,
		/obj/item/melee/chainofcommand/tailwhip = 1,
		/obj/item/melee/flyswatter = 1,
		/obj/item/melee/skateboard/hoverboard = 1,
		/obj/item/reagent_containers/food/drinks/waterbottle/relic = 1,
		/obj/item/rsf = 1,
		/obj/item/rupee = 1,
		/obj/item/sord = 1,
		/obj/item/stack/sheet/meat/fifty = 1,
		/obj/item/stack/telecrystal/five = 1,
		/obj/item/stack/telecrystal = 1,
		/obj/item/storage/belt/utility/syndicate = 1,
		/obj/item/storage/box/firecrackers = 1,
		/obj/item/storage/box/fireworks/dangerous = 1,
		/obj/item/storage/box/hug/medical = 1,
		/obj/item/storage/firstaid/ancient = 1,
		/obj/item/storage/toolbox/emergency/old = 1,
		/obj/item/storage/toolbox/mechanical/old = 1,
		/obj/item/tailclub = 1,
		/obj/item/taster = 1,


	) = 5,
	list( //Meme-level injectors
		/obj/item/dnainjector/chavmut = 1,
		/obj/item/dnainjector/clumsymut = 1,
		/obj/item/dnainjector/dwarf = 1,
		/obj/item/dnainjector/elvismut = 1,
		/obj/item/dnainjector/epimut = 1,
		/obj/item/dnainjector/gigantism = 1,
		/obj/item/dnainjector/glow = 1,
		/obj/item/dnainjector/timed/h2m = 1,
		/obj/item/dnainjector/paranoia = 1,
		/obj/item/dnainjector/spastic = 1,
		/obj/item/dnainjector/stuttmut = 1
		/obj/item/dnainjector/swedishmut = 1,
		/obj/item/dnainjector/tourmut = 1,
		/obj/item/dnainjector/unintelligiblemut = 1,
		/obj/item/dnainjector/wackymut = 1

	) = 1,
	list( //Strong as fuck injectors
		/obj/item/dnainjector/timed/hulk = 1,
		/obj/item/dnainjector/insulated = 1,
		/obj/item/dnainjector/olfaction = 1,
		/obj/item/dnainjector/shock = 1,
		/obj/item/dnainjector/thermal = 1,
		/obj/item/dnainjector/void = 1,
		/obj/item/dnainjector/xraymut = 1
	) = 1,
	list( //INSULS!
		/obj/item/clothing/gloves/color/yellow = 100,
		/obj/item/clothing/gloves/combat = 10,
		/obj/item/clothing/gloves/color/red/insulated = 50
		/obj/item/clothing/gloves/tackler/combat/insulated = 5,
	) = 1
	list( //Misc
		/obj/item/book/granter/crafting_recipe/cooking_sweets_101 = 1
	) = 1,
	list( //Fake objects meant to trick players into thinking they're other items.
		/obj/item/fakeartefact = 100,
		/obj/item/card/emagfake = 1,
		/obj/item/cardboard_cutout = 1,
		/obj/item/clothing/gloves/cut = 1,
		/obj/item/clothing/head/chefhat = 1,
		/obj/item/clothing/head/helmet/old = 1,
		/obj/item/clothing/suit/armor/vest/old = 1,
		/obj/item/clothing/mask/animal/cowmask = 1,
		/obj/item/clothing/mask/animal/frog = 1,
		/obj/item/clothing/mask/animal/horsehead = 1,
		/obj/item/clothing/mask/animal/pig = 1,
		/obj/item/clothing/neck/tie/black = 1,
		/obj/item/clothing/shoes/clown_shoes = 1,
		/obj/item/clothing/shoes/sneakers/black = 1,
		/obj/item/clothing/under/color/black = 1,
		/obj/item/dice/d20 = 1,
		/obj/item/food/monkeycube = 1,
		/obj/item/hot_potato/harmless = 1,
		/obj/item/implanter/sad_trombone = 1,
		/obj/item/reagent_containers/food/drinks/waterbottle = 1,
		/obj/item/soapstone/empty = 1,
		/obj/item/stamp = 1,
		/obj/item/storage/backpack = 1,
		/obj/item/storage/belt = 1,
		/obj/item/storage/belt/holster = 1,
		/obj/item/storage/box/fakesyndiesuit = 1
	) = 10,
	list( //Weapons that are good but not that good.
		/obj/item/claymore/weak/ceremonial = 1,
		/obj/item/chainsaw = 1,
		/obj/item/reagent_containers/glass/bottle/random_virus = 1,
		/obj/item/flamethrower/full/tank = 1,
		/obj/item/gun/ballistic/revolver/rifle/improvised = 1,
		/obj/item/gun/ballistic/shotgun/doublebarrel/improvised = 1,
		/obj/item/scythe = 1,
		/obj/item/throwing_star = 1,
		/obj/item/throwing_star/stamina = 1
	) = 1
	list = (//Chameleon gear
		/obj/item/clothing/glasses/chameleon = 1,
		/obj/item/clothing/glasses/chameleon/broken = 1,
		/obj/item/clothing/gloves/chameleon = 1,
		/obj/item/clothing/gloves/chameleon/broke = 1
		/obj/item/clothing/head/chameleon = 1,
		/obj/item/clothing/head/chameleon/broke = 1,
		/obj/item/clothing/mask/chameleon = 1,
		/obj/item/clothing/mask/chameleon/broken = 1,
		/obj/item/clothing/neck/chameleon = 1,
		/obj/item/clothing/neck/chameleon/broken = 1,
		/obj/item/clothing/shoes/chameleon/noslip = 1,
		/obj/item/clothing/shoes/chameleon/noslip/broken = 1,
		/obj/item/clothing/suit/chameleon = 1,
		/obj/item/clothing/suit/chameleon/broken = 1,
		/obj/item/clothing/under/chameleon = 1,
		/obj/item/clothing/under/chameleon/broken = 1,
		/obj/item/radio/headset/chameleon = 1,
		/obj/item/radio/headset/chameleon/broken = 1,
		/obj/item/stamp/chameleon = 1,
		/obj/item/stamp/chameleon/broken = 1,
		/obj/item/storage/backpack/chameleon = 1,
		/obj/item/storage/backpack/chameleon/broken = 1,
		/obj/item/storage/belt/chameleon = 1,
		/obj/item/storage/belt/chameleon/broken = 1,
		/obj/item/storage/belt/holster/chameleon = 1,
		/obj/item/storage/belt/holster/chameleon/broken = 1
	) = 1,
	list = (//Department analyzers
		/obj/item/clothing/glasses/hud/diagnostic = 1,
		/obj/item/clothing/glasses/hud/health = 1,
		/obj/item/clothing/glasses/hud/security = 1,
		/obj/item/clothing/glasses/night = 1
	) = 20,
	list = (//Potion seller, give me your strongest potions
		/obj/item/eldritch_potion/crucible_soul = 1,
		/obj/item/eldritch_potion/duskndawn = 1,
		/obj/item/eldritch_potion/wounded = 1
	) = 1


))

GLOBAL_LIST_INIT(oddity_loot, list(//oddity: strange or crazy items
		/obj/item/a_gift/anything = 1,
		/obj/item/abductor/silencer = 1,
		/obj/item/abductor/gizmo = 1,
		/obj/item/abductor_machine_beacon/chem_dispenser = 1,
		/obj/item/ai_module/core/full/balance = 1,
		/obj/item/ai_module/core/full/hulkamania = 1,
		/obj/item/ai_module/core/full/liveandletlive = 1,
		/obj/item/ai_module/ion = 1,
		/obj/item/ai_module/toy_ai = 1
		/obj/item/airlock_painter/decal/debug = 1,
		/obj/item/antag_spawner/slaughter_demon/laughter = 1,
		/obj/item/autosurgeon/organ/cmo = 1,
		/obj/item/batterer = 1,
		/obj/item/book/granter/spell/random = 1,
		/obj/item/book_of_babel = 1,
		/obj/item/camera/rewind = 1,
		/obj/item/camera/spooky/badmin = 1,
		/obj/item/camera/timefreeze = 1,
		/obj/item/cartridge/virus/frame = 1
		/obj/item/chameleon = 1,
		/obj/item/clothing/gloves/krav_maga/combatglovesplus = 1,
		/obj/item/clothing/gloves/rapid = 1,
		/obj/item/grenade/clusterbuster/random = 1,
		/obj/item/clothing/head/hardhat/cakehat/energycake = 1,
		/obj/item/clothing/head/sombrero/shamebrero = 1,
		/obj/item/clothing/mask/animal/cowmask/cursed = 1,
		/obj/item/clothing/mask/animal/frog/cursed = 1,
		/obj/item/clothing/mask/animal/horsehead/cursed = 1,
		/obj/item/clothing/mask/animal/pig/cursed = 1,
		/obj/item/clothing/mask/void_mask = 1,
		/obj/item/clothing/shoes/bhop = 1,
		/obj/item/clothing/shoes/clown_shoes/banana_shoes/combat = 1,
		/obj/item/clothing/shoes/winterboots/ice_boots/ice_trail = 1,
		/obj/item/clothing/suit/hooded/bloated_human = 1
		/obj/item/clothing/suit/poncho/ponchoshame = 1,
		/obj/item/desynchronizer = 1,
		/obj/item/devices/ocd_device = 1,
		/obj/item/dice/d20/fate/stealth/one_use = 1,
		/obj/item/dice/d20/fate/stealth/cursed/one_use = 1,
		/obj/item/dnainjector/lasereyesmut = 1,
		/obj/item/dnainjector/mindread = 1,
		/obj/item/dnainjector/telemut/darkbundle = 1,
		/obj/item/door_remote/omni = 1,
		/obj/item/dualsaber = 1,
		/obj/item/firing_pin/paywall = 1,
		/obj/item/firing_pin/dna/dredd = 1,
		/obj/item/food/pizza/arnold = 1,
		/obj/item/gibtonite = 1,
		/obj/item/grenade/chem_grenade/teargas/moustache = 1,
		/obj/item/grenade/clusterbuster/antiweed = 1,
		/obj/item/grenade/clusterbuster/cleaner = 1,
		/obj/item/grenade/clusterbuster/metalfoam = 1,
		/obj/item/grenade/clusterbuster/smoke = 1,
		/obj/item/grenade/clusterbuster/soap = 1,
		/obj/item/grenade/clusterbuster/teargas = 1
		/obj/item/grenade/hypnotic = 1,
		/obj/item/grenade/spawnergrenade/clown = 1,
		/obj/item/gun/ballistic/automatic/pistol/stickman = 1,
		/obj/item/gun/energy/meteorgun/pen = 1,
		/obj/item/gun/energy/shrink_ray = 1,
		/obj/item/gun/magic/staff/locker = 1,
		/obj/item/healthanalyzer/rad_laser = 1,
		/obj/item/hot_potato = 1,
		/obj/item/katana/cursed = 1,
		/obj/item/katana = 1,
		/obj/item/melee/baseball_bat/homerun = 1,
		/obj/item/melee/skateboard/hoverboard/admin = 1,
		/obj/item/mushpunch = 1,
		/obj/item/pen/edagger = 1,
		/obj/item/pen/fountain/captain = 1,
		/obj/item/pizzabox/infinite = 1,
		/obj/item/reagent_containers/food/drinks/bottle/holywater/hell = 1,
		/obj/item/relic = 1,
		/obj/item/sharpener = 1,
		/obj/item/sharpener/super = 1,
		/obj/item/stack/sticky_tape/super = 1,
		/obj/item/stack/sticky_tape/pointy = 1,
		/obj/item/stack/sticky_tape/pointy/super = 1,
		/obj/item/storage/box/donkpockets/donkpocketgondola = 1,
		/obj/item/storage/box/gorillacubes = 1,
		/obj/item/storage/box/gum/bubblegum = 1
		/obj/item/storage/box/hug/reverse_revolver = 1,
		/obj/item/storage/box/material = 1,
		/obj/item/storage/toolbox/syndicate = 1.
		/obj/item/storage/toolbox/infiltrator = 1,
		/obj/item/suspiciousphone = 1,
		/obj/item/toy/sprayoncan = 1,
		/obj/item/uplink/old = 1,
		/obj/item/voodoo = 1,
		/obj/item/warpwhistle = 1,

















	))

//Maintenance loot spawner pools
#define maint_trash_weight 4499
#define maint_common_weight 4500
#define maint_uncommon_weight 1000
#define maint_oddity_weight 1 //1 out of 10,000 would give metastation (180 spawns) a 2 in 111 chance of spawning an oddity per round, similar to xeno egg
#define maint_holiday_weight 3500 // When holiday loot is enabled, it'll give every loot item a 25% chance of being a holiday item

//Loot pool used by default maintenance loot spawners
GLOBAL_LIST_INIT(maintenance_loot, list(
	GLOB.trash_loot = maint_trash_weight,
	GLOB.common_loot = maint_common_weight,
	GLOB.uncommon_loot = maint_uncommon_weight,
	GLOB.oddity_loot = maint_oddity_weight,
	))

GLOBAL_LIST_INIT(ratking_trash, list(//Garbage: used by the regal rat mob when spawning garbage.
			/obj/item/cigbutt,
			/obj/item/trash/cheesie,
			/obj/item/trash/candy,
			/obj/item/trash/chips,
			/obj/item/trash/pistachios,
			/obj/item/trash/plate,
			/obj/item/trash/popcorn,
			/obj/item/trash/raisins,
			/obj/item/trash/sosjerky,
			/obj/item/trash/syndi_cakes))

GLOBAL_LIST_INIT(ratking_coins, list(//Coins: Used by the regal rat mob when spawning coins.
			/obj/item/coin/iron,
			/obj/item/coin/silver,
			/obj/item/coin/plastic,
			/obj/item/coin/titanium))
