#define BAN_PACIFICATION "Pacification ban"
#define BAN_DONOTREVIVE "Do not revive ban"
#define BAN_RESPAWN "Respawn ban"
#define BAN_MOB_CONTROL "Ghost mob control ban"
#define BAN_GHOST_ROLE_SPAWNER "Ghost role spawner ban"
#define BAN_GHOST_TAKEOVER "Ghost candidate ban"
#define BAN_EORG "EORG ban"
