//MODULE BLUESHIELD DEFINES

//MODULE BLUESHIELD DEFINES access.dm
#define ACCESS_BLUESHIELD 73
//MODULE END

//MODULE BLUESHIELD DEFINES jobs.dm
#define BLUESHIELD		(1<<15)
#define JOB_DISPLAY_ORDER_BLUESHIELD 34
//MODULE END

