// Bitflags for what company a cargo order datum should belong to
#define CARGO_COMPANY_NAKAMURA (1<<0)
#define CARGO_COMPANY_BLACKSTEEL (1<<1)
#define CARGO_COMPANY_NRI_SURPLUS (1<<2)
#define CARGO_COMPANY_DEFOREST (1<<3)

#define COMPANY_INTEREST_GAIN_BIG 10
#define COMPANY_INTEREST_GAIN_AVERAGE 5
#define COMPANY_INTEREST_GAIN_LOW 3
#define COMPANY_INTEREST_GAIN_PITIFUL 1
