#define ACCESS_FACTION_PUBLIC 401
#define ACCESS_FACTION_CREW 402
#define ACCESS_FACTION_COMMAND 403

#define RADIO_CHANNEL_FACTION "Faction"
#define RADIO_KEY_FACTION "f"
#define RADIO_TOKEN_FACTION ":f"

#define FREQ_FACTION 1335
