// Bitflags for what company produces the gun
#define COMPANY_CANTALAN (1<<0)
#define COMPANY_ARMADYNE (1<<1)
#define COMPANY_SCARBOROUGH (1<<2)
#define COMPANY_DONK (1<<3)
#define COMPANY_BOLT (1<<4)
#define COMPANY_OLDARMS (1<<5)
#define COMPANY_IZHEVSK (1<<6)
#define COMPANY_NANOTRASEN (1<<7)
#define COMPANY_ALLSTAR (1<<8)
#define COMPANY_MICRON (1<<9)
#define COMPANY_DYNAMICS (1<<10)
#define COMPANY_INTERDYNE (1<<12)
#define COMPANY_JARNSMIOUR (1<<13)
#define COMPANY_ABDUCTOR (1<<14)
#define COMPANY_REMOVED (1<<15)
#define COMPANY_TKACH (1<<16)
