#define RADIO_CHANNEL_CYBERSUN "Cybersun"
#define RADIO_KEY_CYBERSUN "q"
#define RADIO_TOKEN_CYBERSUN ":q"

#define FREQ_CYBERSUN 1211

#define RADIO_CHANNEL_INTERDYNE "Interdyne"
#define RADIO_KEY_INTERDYNE "w"
#define RADIO_TOKEN_INTERDYNE ":w"

#define FREQ_INTERDYNE 1209

#define RADIO_CHANNEL_GUILD "Guild"
#define RADIO_KEY_GUILD "p"
#define RADIO_TOKEN_GUILD ":p"

#define FREQ_GUILD 1214

#define RADIO_CHANNEL_TARKON "Tarkon"
#define RADIO_KEY_TARKON "k"
#define RADIO_TOKEN_TARKON ":k"

#define FREQ_TARKON 1243


#define RADIO_CHANNEL_SOLFED "SolFed"
#define RADIO_KEY_SOLFED "l"
#define RADIO_TOKEN_SOLFED ":l"

#define FREQ_SOLFED 1205

#define RADIO_CHANNEL_ARMADYNE "Armadyne"
#define RADIO_KEY_ARMADYNE "r"
#define RADIO_TOKEN_ARMADYNE ":r"

#define FREQ_ARMADYNE 1207
