#define RADIO_CHANNEL_CYBERSUN "Cybersun"
#define RADIO_KEY_CYBERSUN "q"
#define RADIO_TOKEN_CYBERSUN ":q"

#define FREQ_CYBERSUN 1211

#define RADIO_CHANNEL_INTERDYNE "Interdyne"
#define RADIO_KEY_INTERDYNE "w"
#define RADIO_TOKEN_INTERDYNE ":w"

#define FREQ_INTERDYNE 1209

#define RADIO_CHANNEL_GUILD "Guild"
#define RADIO_KEY_GUILD "g"
#define RADIO_TOKEN_GUILD ":g"

#define FREQ_GUILD 1214

#define RADIO_CHANNEL_TARKON "Tarkon"
#define RADIO_KEY_TARKON "k"
#define RADIO_TOKEN_TARKON ":k"

#define FREQ_TARKON 1243
