#define ZTRAITS_ROCKPLANET list(\
	ZTRAIT_MINING = TRUE, \
	ZTRAIT_ACIDRAIN = TRUE, \
	ZTRAIT_LAVA_RUINS = TRUE, \
	ZTRAIT_BOMBCAP_MULTIPLIER = 2, \
	ZTRAIT_BASETURF = /turf/open/floor/plating/asteroid)
