// IF YOU ARE ADDING A NEW MAP, ENSURE YOU DEFINE THE LEVEL TRAITS AND A KEYWORD TO LOAD THEM WITH.
// THE CONFIG USES THE KEYWORD TO LOAD THE ASSIGNED TRAITS.

GLOBAL_LIST_INIT(mining_traits, list(
	"lavaland" = ZTRAITS_LAVALAND,
	"rockplanet" = ZTRAITS_ROCKPLANET,
	"icemoon" = ZTRAITS_ICEMOONSKYRAT,
	"tidallock" = ZTRAITS_TIDALLOCK
))
