#define OPFOR_BACKSTORY_MIN_CHARS 100
#define OPFOR_BACKSTORY_MAX_CHARS 500

#define OPFOR_MAX_OBJECTIVES 5

#define OPFOR_STATUS_NOT_SUBMITTED "Not submitted"
#define OPFOR_STATUS_APPROVED "Approved"
#define OPFOR_STATUS_DENIED "Denied"
#define OPFOR_STATUS_AWAITING_APPROVAL "Awaiting approval"
#define OPFOR_STATUS_CHANGES_REQUESTED "Changes requested"

#define OPFOR_OBJECTIVE_STATUS_NOT_REVIEWED "Not Reviewed"
#define OPFOR_OBJECTIVE_STATUS_APPROVED "Approved"
#define OPFOR_OBJECTIVE_STATUS_DENIED "Denied"

#define OPFOR_OBJECTIVE_INTENSITY_1 "1 - Minor theft or basic antagonizing"
#define OPFOR_OBJECTIVE_INTENSITY_2 "2 - Kidnapping / Theft"
#define OPFOR_OBJECTIVE_INTENSITY_3 "3 - Assassination / Grand Theft"
#define OPFOR_OBJECTIVE_INTENSITY_4 "4 - Mass sabotage (engine delamination)"
#define OPFOR_OBJECTIVE_INTENSITY_5 "5 - Mass destruction or mass killings"

#define OPFOR_SUBSYSTEM_REJECT_CAP "OPFOR application system has reached the maximum number of applications"
#define OPFOR_SUBSYSTEM_REJECT_CLOSED "OPFOR application system is not accepting new applications"
#define OPFOR_SUBSYSTEM_READY "OPFOR application system is ready to accept new applications"

#define OPFOR_REQUEST_UPDATE_COOLDOWN 5 MINUTES
#define OPFOR_PING_COOLDOWN 1 MINUTES

#define OPFOR_TEXT_LIMIT_TITLE 40
#define OPFOR_TEXT_LIMIT_BACKSTORY 1000
#define OPFOR_TEXT_LIMIT_DESCRIPTION 500
#define OPFOR_TEXT_LIMIT_JUSTIFICATION 500
#define OPFOR_TEXT_LIMIT_MESSAGE 300

#define OPFOR_EQUIPMENT_LIMIT 10
#define OPFOR_EQUIPMENT_COUNT_LIMIT 5

#define OPFOR_EQUIPMENT_STATUS_NOT_REVIEWED "Not Reviewed"
#define OPFOR_EQUIPMENT_STATUS_APPROVED "Approved"
#define OPFOR_EQUIPMENT_STATUS_DENIED "Denied"

// EQUIPMENT CATEGORIES
#define OPFOR_EQUIPMENT_CATEGORY_PISTOLS "Pistols"
#define OPFOR_EQUIPMENT_CATEGORY_SUBMACHINE_GUNS "Submachine Guns"
#define OPFOR_EQUIPMENT_CATEGORY_RIFLES "Rifles"
#define OPFOR_EQUIPMENT_CATEGORY_SHOTGUNS "Shotguns"
#define OPFOR_EQUIPMENT_CATEGORY_MELEE_WEAPONS "Melee Weapons"
#define OPFOR_EQUIPMENT_CATEGORY_AMMUNITION "Ammunition"
#define OPFOR_EQUIPMENT_CATEGORY_CLOTHING "Clothing"
#define OPFOR_EQUIPMENT_CATEGORY_UTILITY "Utility"
#define OPFOR_EQUIPMENT_CATEGORY_EXPLOSIVES "Explosives"
#define OPFOR_EQUIPMENT_CATEGORY_LOADOUT "Loadouts"
#define OPFOR_EQUIPMENT_CATEGORY_OTHER "Other"
#define OPFOR_EQUIPMENT_CATEGORY_MARTIAL_ARTS "Martial Arts"
#define OPFOR_EQUIPMENT_CATEGORY_SERVICES "Services"
#define OPFOR_EQUIPMENT_CATEGORY_SPELLS "Spells"
#define OPFOR_EQUIPMENT_CATEGORY_IMPLANTS "Implants"
