#define OUTBOUND_WIRE_COUNT 12
#define OUTBOUND_WIRE_COLORS list(COLOR_RED, COLOR_GRAY, COLOR_ORANGE, COLOR_YELLOW, COLOR_GREEN, COLOR_BLUE, COLOR_PURPLE, COLOR_VIOLET, COLOR_NAVY, COLOR_CYAN, COLOR_MAROON)
