// CONSTRUCTION STATES
#define PA_CONSTRUCTION_UNSECURED  0
#define PA_CONSTRUCTION_UNWIRED    1
#define PA_CONSTRUCTION_PANEL_OPEN 2
#define PA_CONSTRUCTION_COMPLETE   3

// POWER STATES
#define PARTICLE_STRENGTH_WEAK 0
#define PARTICLE_STRENGTH_NORMAL 1
#define PARTICLE_STRENGTH_STRONG 2
#define PARTICLE_STRENGTH_MAX 3

#define ENERGY_REQ_SINGULARITY_CREATION 200

#define SINGULARITY_EFFECT_ANIM_TIME 62
