#define DEFAULT_MAX_VELOCITY 100
#define DEFAULT_MAX_THRUST_VELOCITY 6

#define THRUST_DIR_FORWARD NORTH
#define THRUST_DIR_BACKWARD SOUTH
#define THRUST_DIR_RIGHT EAST
#define THRUST_DIR_LEFT WEST
#define THRUST_DIR_STOP 0

#define TRIGONOMETRIC_EPSILON_THRESHOLD 1e-10
