#define THRUST_DIR_FORWARD NORTH
#define THRUST_DIR_BACKWARDS SOUTH
#define THRUST_DIR_RIGHT EAST
#define THRUST_DIR_LEFT WEST
#define THRUST_DIR_STOP 0

#define TRIGONOMETRIC_EPSILON_THRESHOLD 1e-10
