#define RND_SUBCATEGORY_MECHFAB_CYBORG_MODULES_CARGO "/Cargo Cyborgs"

/// Spacepod stuff
#define RND_CATEGORY_SPACEPOD "/Spacepod"

#define RND_SUBCATEGORY_SPACEPOD_CORE_SYSTEMS "/Core Systems"
#define RND_SUBCATEGORY_SPACEPOD_LOCKING_SYSTEMS "/Locking Systems"
#define RND_SUBCATEGORY_SPACEPOD_WEAPON_SYSTEMS "/Weapon Systems"
#define RND_SUBCATEGORY_SPACEPOD_ARMOR_SYSTEMS "/Armor Systems"
#define RND_SUBCATEGORY_SPACEPOD_CARGO_SYSTEMS "/Cargo Systems"
#define RND_SUBCATEGORY_SPACEPOD_MISC_SYSTEMS "/Misc Systems"
#define RND_SUBCATEGORY_SPACEPOD_ENGINE_SYSTEMS "/Engine Systems"
