#define RESKIN_ICON "reskin_icon"
#define RESKIN_ICON_STATE "reskin_icon_state"
#define RESKIN_WORN_ICON "reskin_worn_icon"
#define RESKIN_WORN_ICON_STATE "reskin_worn_icon_state"
#define RESKIN_MUTANT_VARIANTS "reskin_mutant_variants"
