#define ROLE_LONE_INFILTRATOR "Lone Infiltrator"
#define ROLE_BORER "Borer"
#define ROLE_DRIFTING_CONTRACTOR "Drifting Contractor"
#define ROLE_ASSAULT_OPERATIVE "Assault Operative"
#define ROLE_MUTANT "Mutated Abomination"
