#define RADIO_CHANNEL_CYBERSUN "Cybersun"
#define RADIO_KEY_CYBERSUN "q"
#define RADIO_TOKEN_CYBERSUN ":q"

#define FREQ_CYBERSUN 1211

#define RADIO_CHANNEL_INTERDYNE "Interdyne"
#define RADIO_KEY_INTERDYNE "w"
#define RADIO_TOKEN_INTERDYNE ":w"

#define FREQ_INTERDYNE 1209

#define RADIO_CHANNEL_ASSAULT "DS-1"
#define RADIO_KEY_ASSAULT "r"
#define RADIO_TOKEN_ASSAULT ":r"

#define FREQ_ASSAULT 1207
