#define MUTANT_SYNTH_ANTENNA "MUTANT_SYNTH_ANTENNA"
#define MUTANT_SYNTH_SCREEN "MUTANT_SYNTH_SCREEN"
#define MUTANT_SYNTH_CHASSIS "MUTANT_SYNTH_CHASSIS"
#define MUTANT_SYNTH_HEAD "MUTANT_SYNTH_HEAD"
