GLOBAL_LIST_EMPTY(captain_alttitles)

GLOBAL_LIST_EMPTY(central_command_alttitles)

GLOBAL_LIST_EMPTY(command_alttitles)

GLOBAL_LIST_EMPTY(engineering_alttitles)

GLOBAL_LIST_EMPTY(medical_alttitles)

GLOBAL_LIST_EMPTY(science_alttitles)

GLOBAL_LIST_EMPTY(supply_alttitles)

GLOBAL_LIST_EMPTY(service_alttitles)

GLOBAL_LIST_EMPTY(security_alttitles)

GLOBAL_LIST_EMPTY(nonhuman_alttitles)
