contact_links:
  - name: Feature Requests
    url: https://github.com/Skyrat-SS13/Skyrat-tg/discussions
    about: Post feature requests and suggestions on the repository, a maintainer will look over them.
