#define WATER_HEIGH_DIFFERENCE_DELTA_SPLASH 16 //Delta needed for the splash effect to be made in 1 go

#define PARTIAL_TRANSFER_AMOUNT 0.3

#define LIQUID_MUTUAL_SHARE 1
#define LIQUID_NOT_MUTUAL_SHARE 2

#define LIQUID_GIVER 1
#define LIQUID_TAKER 2

#define LIQUID_HEIGHT_DIVISOR 20

#define SSLIQUIDS_RUN_TYPE_TURFS 1
#define SSLIQUIDS_RUN_TYPE_GROUPS 2

#define LIQUID_GROUP_DECAY_TIME 3
