#define BIO_BLOB_TYPE_FUNGUS "fungus"
#define BIO_BLOB_TYPE_FIRE "fire"
#define BIO_BLOB_TYPE_EMP "emp"
#define BIO_BLOB_TYPE_TOXIC "toxic"
#define ALL_BIO_BLOB_TYPES list(BIO_BLOB_TYPE_FUNGUS, BIO_BLOB_TYPE_FIRE, BIO_BLOB_TYPE_EMP, BIO_BLOB_TYPE_TOXIC)

#define MOLD_FACTION "mold"
