/obj/effect/spawner/random/deep_maintenance/mothic_ration_crate
	name = "deepmaint moth ration spawner"
	replacement_closet = /obj/structure/closet/crate/cardboard/mothic
	loot = list(
		// Food items
		/obj/item/food/sustenance_bar = 3,
		/obj/item/food/sustenance_bar/cheese = 2,
		/obj/item/food/sustenance_bar/mint = 2,
		/obj/item/food/sustenance_bar/neapolitan = 2,
		/obj/item/food/vendor_snacks/mothmallow = 1,
		/obj/item/food/vendor_snacks/moth_bag = 3,
		/obj/item/food/vendor_snacks/moth_bag/cheesecake = 2,
		/obj/item/food/vendor_snacks/moth_bag/cheesecake/honey = 2,
		/obj/item/food/vendor_snacks/moth_bag/fuel_jack = 3,
		/obj/item/food/vendor_tray_meal/side/cornbread = 2,
		/obj/item/food/vendor_tray_meal/side/moffin = 2,
		/obj/item/food/vendor_tray_meal/side/roasted_seeds = 2,
		// Ingredients
		/obj/item/reagent_containers/cup/glass/bottle/juice/limejuice = 2,
		/obj/item/reagent_containers/cup/glass/bottle/juice/orangejuice = 2,
		/obj/item/reagent_containers/cup/glass/bottle/juice/pineapplejuice = 2,
		/obj/item/reagent_containers/condiment/milk = 1,
		/obj/item/reagent_containers/condiment/sugar/small_ration = 2,
		/obj/item/reagent_containers/condiment/flour/small_ration = 2,
		/obj/item/reagent_containers/condiment/small_ration_korta_flour = 2,
		/obj/item/reagent_containers/condiment/cherryjelly = 1,
		/obj/item/reagent_containers/condiment/rice/small_ration = 2,
		/obj/item/reagent_containers/condiment/soymilk/small_ration = 2,
		/obj/item/reagent_containers/condiment/cornmeal = 1,
		/obj/item/storage/box/spaceman_ration/meats = 1,
		/obj/item/storage/box/spaceman_ration/meats/fish = 1,
		/obj/item/storage/box/spaceman_ration/plants/mothic = 2,
		/obj/item/storage/box/papersack/ration_bread_slice = 1,
		/obj/item/storage/box/mothic_cans_sauces = 1,
		/obj/item/storage/box/mothic_goods = 1,
		/obj/item/storage/box/mothic_rations = 1,
	)

/obj/effect/spawner/random/deep_maintenance/mothic_ration_crate
	name = "deepmaint food spawner"
	replacement_closet = /obj/structure/closet/crate/freezer/food
	loot = list(
		// Food items
		/obj/item/food/bluefeather_crisp = 3,
		/obj/item/food/brain_pate = 2,
		/obj/item/food/branrequests = 3,
		/obj/item/food/breadslice/corn = 2,
		/obj/item/food/breadslice/reispan = 2,
		/obj/item/food/breadslice = 2,
		/obj/item/food/breadslice/root = 2,
		/obj/item/food/butter = 3,
		/obj/item/food/candy = 3,
		/obj/item/food/canned/beans = 3,
		/obj/item/food/canned/peaches = 3,
		/obj/item/food/canned/tomatoes = 3,
		/obj/item/food/canned/tuna = 3,
		/obj/item/food/cheese/firm_cheese_slice = 2,
		/obj/item/food/cheese/firm_cheese = 1,
		/obj/item/food/chocolatebar = 2,
		/obj/item/food/cnds/random = 3,
		/obj/item/food/colonial_course/pljeskavica = 1,
		/obj/item/food/colonial_course/nachos = 1,
		/obj/item/food/colonial_course/blins = 1,
		/obj/item/food/cornchips/random = 2,
		/obj/item/food/peanuts/random = 2,
		/obj/item/food/ready_donk = 1,
		/obj/item/food/ready_donk/donkhiladas = 1,
		/obj/item/food/ready_donk/donkrange_chicken = 1,
		/obj/item/food/ready_donk/mac_n_cheese = 1,
		/obj/item/food/ready_donk/nachos_grandes = 1,
		/obj/item/food/semki = 3,
		/obj/item/food/spacers_sidekick = 2,
		/obj/item/food/sticko/random = 3,
		// Ingredients
		/obj/item/reagent_containers/cup/glass/bottle/juice/limejuice = 2,
		/obj/item/reagent_containers/cup/glass/bottle/juice/orangejuice = 2,
		/obj/item/reagent_containers/cup/glass/bottle/juice/pineapplejuice = 2,
		/obj/item/reagent_containers/condiment/milk = 1,
		/obj/item/reagent_containers/condiment/sugar/small_ration = 2,
		/obj/item/reagent_containers/condiment/flour/small_ration = 2,
		/obj/item/reagent_containers/condiment/small_ration_korta_flour = 2,
		/obj/item/reagent_containers/condiment/cherryjelly = 1,
		/obj/item/reagent_containers/condiment/rice/small_ration = 2,
		/obj/item/reagent_containers/condiment/soymilk/small_ration = 2,
		/obj/item/reagent_containers/condiment/cornmeal = 1,
		/obj/item/storage/box/spaceman_ration/meats = 1,
		/obj/item/storage/box/spaceman_ration/meats/lizard = 1,
		/obj/item/storage/box/spaceman_ration/meats/fish = 1,
		/obj/item/storage/box/spaceman_ration/plants = 2,
		/obj/item/storage/box/spaceman_ration/plants/alternate = 2,
		/obj/item/storage/box/spaceman_ration/plants/lizard = 2,
		/obj/item/storage/box/spaceman_ration/plants/mothic = 2,
		/obj/item/storage/box/papersack/ration_bread_slice = 1,
		/obj/item/storage/box/colonial_rations = 1,
		// We can slip some ration tickets in here too because why not?
		/obj/item/paper/paperslip/ration_ticket = 1,
		/obj/item/paper/paperslip/ration_ticket/luxury = 1,
	)
