//Port Tarkon Incinerator
#define INCINERATOR_TARKON_IGNITER "tarkon_igniter"
#define INCINERATOR_TARKON_DP_VENTPUMP "tarkon_airlock_pump"
#define INCINERATOR_TARKON_AIRLOCK_SENSOR "tarkon_airlock_sensor"
#define INCINERATOR_TARKON_AIRLOCK_CONTROLLER "tarkon_airlock_controller"
#define INCINERATOR_TARKON_AIRLOCK_INTERIOR "tarkon_airlock_interior"
#define INCINERATOR_TARKON_AIRLOCK_EXTERIOR "tarkon_airlock_exterior"

#define ATMOS_GAS_MONITOR_TARKON_O2 "tarkon_o2"
#define ATMOS_GAS_MONITOR_TARKON_PLAS "tarkon_plas"
#define ATMOS_GAS_MONITOR_TARKON_MIX "tarkon_mix"
#define ATMOS_GAS_MONITOR_TARKON_N2 "tarkon_n2"
#define ATMOS_GAS_MONITOR_TARKON_N2O "tarkon_n2o"
#define ATMOS_GAS_MONITOR_TARKON_CO2 "tarkon_co2"
#define ATMOS_GAS_MONITOR_TARKON_INCINERATOR "tarkon_incinerator"
