mode = "BitmaskSlice"
produce_dirs = false
smooth_diagonally = true

[icon_size]
x = 42
y = 64

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 42
y = 64

[cut_pos]
x = 21
y = 32

[positions]
convex = 0
vertical = 1
concave = 2
horizontal = 3
flat = 4
