#define SSDISPATCH_TICKET_TYPE_SECURITY "Security"
#define SSDISPATCH_TICKET_TYPE_ENGINEERING "Engineering"
#define SSDISPATCH_TICKET_TYPE_MEDICAL "Medical"
#define SSDISPATCH_TICKET_TYPES list( \
	SSDISPATCH_TICKET_TYPE_SECURITY,\
	SSDISPATCH_TICKET_TYPE_ENGINEERING,\
	SSDISPATCH_TICKET_TYPE_MEDICAL)
#define SSDISPATCH_TICKET_TYPES_DEPT list( \
	SSDISPATCH_TICKET_TYPE_SECURITY = DEPARTMENT_SECURITY,\
	SSDISPATCH_TICKET_TYPE_MEDICAL = DEPARTMENT_MEDICAL,\
	SSDISPATCH_TICKET_TYPE_ENGINEERING = DEPARTMENT_ENGINEERING)

#define SSDISPATCH_TICKET_PRIORITY_MINIMAL "Minimal"
#define SSDISPATCH_TICKET_PRIORITY_LOW "Low"
#define SSDISPATCH_TICKET_PRIORITY_NORMAL "Normal"
#define SSDISPATCH_TICKET_PRIORITY_HIGH "High"
#define SSDISPATCH_TICKET_PRIORITY_CRITICAL "Critical"
#define SSDISPATCH_TICKET_PRIORITIES list( \
	SSDISPATCH_TICKET_PRIORITY_MINIMAL,\
	SSDISPATCH_TICKET_PRIORITY_LOW,\
	SSDISPATCH_TICKET_PRIORITY_NORMAL,\
	SSDISPATCH_TICKET_PRIORITY_HIGH,\
	SSDISPATCH_TICKET_PRIORITY_CRITICAL)

#define SSDISPATCH_TICKET_STATUS_OPEN "Open"
#define SSDISPATCH_TICKET_STATUS_RESOLVED "Resolved"
#define SSDISPATCH_TICKET_STATUS_REJECTED "Rejected"
#define SSDISPATCH_TICKET_STATUS_ACTIVE "Active"
#define SSDISPATCH_TICKET_STATUSES list( \
	SSDISPATCH_TICKET_STATUS_OPEN,\
	SSDISPATCH_TICKET_STATUS_RESOLVED,\
	SSDISPATCH_TICKET_STATUS_REJECTED,\
	SSDISPATCH_TICKET_STATUS_ACTIVE)
