/obj/item/gun/ballistic/automatic/pitbull/odst
	name = "Specialized 'Pitbull' Battle Rifle"
	desc = "A specialized battle rifle designed for ODST squads."
	icon = 'modular_skyrat/modules/additionalert/odst/icons/guns/gun_odst.dmi'
	righthand_file = 'modular_skyrat/modules/additionalert/odst/icons/guns/righthand.dmi'
	lefthand_file = 'modular_skyrat/modules/additionalert/odst/icons/guns/lefthand.dmi'
	inhand_icon_state = "pitbull"
	icon_state = "pitbull_odst"
	worn_icon = 'modular_skyrat/modules/additionalert/odst/icons/guns/ostwind.dmi'
	worn_icon_state = "ostwind_worn"
	w_class = WEIGHT_CLASS_BULKY
	slot_flags = ITEM_SLOT_BACK | ITEM_SLOT_BELT | ITEM_SLOT_OCLOTHING
	mag_type = /obj/item/ammo_box/magazine/multi_sprite/pitbull
	fire_delay = 2
	can_suppress = FALSE
	burst_size = 3
	fire_delay = 3
	spread = 5
	mag_display = TRUE
	mag_display_ammo = FALSE
	realistic = TRUE
	fire_sound = 'modular_skyrat/modules/additionalert/odst/sound/smg_fire.ogg'
	emp_damageable = FALSE
	armadyne = TRUE
	can_bayonet = TRUE
	can_flashlight = TRUE
