//Process times
#define MOB_PROCESS_INTERVAL	2 SECONDS
#define FAST_PROCESS_INTERVAL	0.2 SECONDS
#define SLOW_PROCESS_INTERVAL	1 MINUTE
#define MACHINE_PROCESS_INTERVAL	2 SECONDS
#define EVENT_PROCESS_INTERVAL	2 SECONDS
