# This mode is for an experiment with directional visibility within one tile.
# It first performs a bitmask slice, and then does an extra cut where it cuts out a "direction"
# version for each direction. This "direction" version is intended to represent what would be
# visible from that side of the wall
mode = "BitmaskDirectionalVis"

produce_dirs = false
smooth_diagonally = true

# These values are "inherited" from BitmaskSlice
# Because the first "phase" is a normal bitmask slice, that step is configured by the same values
# see the bitmask-slice example for what these do!
[icon_size]
x = 32
y = 48

[output_icon_pos]
x = 0
y = 0

[output_icon_size]
x = 32
y = 48

[cut_pos]
x = 16
y = 12

[positions]
convex = 0
concave = 1
horizontal = 2
vertical = 3
flat = 4

# This is the actual new config of dir visibility
# This represents the line at which to make the cut
# the section opposite the side declared gets discarded
# Ex: the west dir cut discards the east side, leaving only the region before the slice point
# The rest becomes transparency.
# "west" and "east" count from the left edge, while "north" and "south" count from the top edge
[slice_point]
west = 4
north = 16
south = 20
east = 28

