directory = "_maps/RandomRuins/SpaceRuins/skyrat/port_tarkon/"

[rooms.xeno]
modules = ["xeno_safe.dmm", "xeno_dead.dmm", "xeno_nest.dmm"]

[rooms.cargo]
modules = ["cargo_stock.dmm", "cargo_warehouse.dmm", "cargo_secure.dmm"]

[rooms.dorm]
modules = ["dorm_classic.dmm", "dorm_cabin.dmm", "dorm_party.dmm"]
