name: PR emoji stripper
on:
  pull_request_target:
    types: [opened, edited]

permissions:
  pull-requests: write

jobs:
  title_and_changelog:
    runs-on: ubuntu-22.04
    steps:
    - uses: Wayland-Smithy/emoji-stripper-action@de0c1d158edee50700583d6454aa5f5117337599
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        title: true
        body: true
        body-after: ":cl:"
        body-before: "/:cl:"
